build:
  image: chef-testing
  environment:
    RACKSPACE_USERNAME: $$RACKSPACE_USERNAME
    RACKSPACE_API_KEY: $$RACKSPACE_API_KEY
  commands:
    - ls -lhRa /drone
    - ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
    - chef exec rubocop
    - chef exec foodcritic .
    - chef exec berks install
    - kitchen test -c -l warn
